### ISSUE TITLE
Container exited with code 2

### ISSUE THREAD

**Issue by Dimitrius-dev** [myelectronix/xtls-reality-docker#4]
Error i got in container:

```
2024/12/17 21:51:54 tcp:109.212.51.201:2908 accepted udp:142.250.179.161:443 [vless_tls >> direct]

2024/12/17 21:51:54 109.212.51.201:2907 accepted tcp:www.google.com:443 [vless_tls >> direct]

panic: runtime error: slice bounds out of range [:2275] with capacity 2048

goroutine 1693 [running]:

github.com/xtls/xray-core/common/protocol/quic.SniffQUIC({0xc00031e000, 0x9c4, 0x2000})

	github.com/xtls/xray-core/common/protocol/quic/sniff.go:220 +0x1c93

github.com/xtls/xray-core/app/dispatcher.NewSniffer.func4({0x84a8ca?, 0xc000500d80?}, {0xc00031e000?, 0x80?, 0x1075180?})

	github.com/xtls/xray-core/app/dispatcher/sniffer.go:40 +0x25

github.com/xtls/xray-core/app/dispatcher.(*Sniffer).Sniff(0xc00055c618, {0x1346f20, 0xc0005d2de0}, {0xc00031e000, 0x9c4, 0x2000}, 0x3)

	github.com/xtls/xray-core/app/dispatcher/sniffer.go:64 +0xdf

github.com/xtls/xray-core/app/dispatcher.sniffer.func1({0x1346f20, 0xc0005d2de0}, 0xc0005d2de0?, 0xc0005d31a0, 0x4103a5?, 0x5d3170?)

	github.com/xtls/xray-core/app/dispatcher/default.go:346 +0x125

github.com/xtls/xray-core/app/dispatcher.sniffer({0x1346f20, 0xc0005d2de0}, 0x1337580?, 0x0, 0x0?)

	github.com/xtls/xray-core/app/dispatcher/default.go:356 +0x10f

github.com/xtls/xray-core/app/dispatcher.(*DefaultDispatcher).Dispatch.func1()

	github.com/xtls/xray-core/app/dispatcher/default.go:241 +0x11c

created by github.com/xtls/xray-core/app/dispatcher.(*DefaultDispatcher).Dispatch in goroutine 1687

	github.com/xtls/xray-core/app/dispatcher/default.go:236 +0x39f
```

I have not idea how to reproduce it. Container had been working for about 2 months good. So now it throws the error after ~30 mins after starting

**Comment by user9155** [comment]
Same for me - working without an issue for 2-4 month, now starting to crash:

```
2025/02/14 13:16:40 89.113.144.194:64274 accepted tcp:www.google.com:443 [vless_tls >> direct]
2025/02/14 13:16:40 89.113.144.194:64275 accepted tcp:update.googleapis.com:443 [vless_tls >> direct]
panic: runtime error: slice bounds out of range [:2066] with capacity 2048

goroutine 34578 [running]:
github.com/xtls/xray-core/common/protocol/quic.SniffQUIC({0xc001258000, 0x4e2, 0x2000})
        github.com/xtls/xray-core/common/protocol/quic/sniff.go:220 +0x1c93
github.com/xtls/xray-core/app/dispatcher.NewSniffer.func4({0x84a8ca?, 0xc00011bb88?}, {0xc001258000?, 0x80?, 0x1075180?})
        github.com/xtls/xray-core/app/dispatcher/sniffer.go:40 +0x25
github.com/xtls/xray-core/app/dispatcher.(*Sniffer).Sniff(0xc002242e70, {0x1346f20, 0xc0005b57a0}, {0xc001258000, 0x4e2, 0x2000}, 0x3)
        github.com/xtls/xray-core/app/dispatcher/sniffer.go:64 +0xdf
github.com/xtls/xray-core/app/dispatcher.sniffer.func1({0x1346f20, 0xc0005b57a0}, 0xc0005b57a0?, 0xc0007e9830, 0x4103a5?, 0x7e97d0?)
        github.com/xtls/xray-core/app/dispatcher/default.go:346 +0x125
github.com/xtls/xray-core/app/dispatcher.sniffer({0x1346f20, 0xc0005b57a0}, 0x0?, 0x0, 0xc0?)
        github.com/xtls/xray-core/app/dispatcher/default.go:356 +0x10f
github.com/xtls/xray-core/app/dispatcher.(*DefaultDispatcher).Dispatch.func1()
        github.com/xtls/xray-core/app/dispatcher/default.go:241 +0x11c
created by github.com/xtls/xray-core/app/dispatcher.(*DefaultDispatcher).Dispatch in goroutine 34575
        github.com/xtls/xray-core/app/dispatcher/default.go:236 +0x39f
XTLS reality starting...
Xray 1.8.4 (Xray, Penetrates Everything.) Custom (go1.21.0 linux/amd64)
A unified platform for anti-censorship.
```
Please let me know what else troubleshooting data you need.

**Comment by user9155** [comment]
Ok, as far as i understand this is just a docker wrap of the original [XTLS/Xray-core](https://github.com/XTLS/Xray-core/) but i couldn't find similar bug there...

**Comment by sen-semilla** [comment]
Had the same issue.
Looks like it is related to the buggy XRAY_CORE_VERSION (v1.8.4).
Forked the project to fix it.
https://github.com/XTLS/Xray-core/issues/2651 - I guess this is related to the current issue.
